"""Export selected Django SQLite rows into D1-friendly SQL.

This helper intentionally exports only records that make sense to preserve when
leaving the ECS MVP. Test users and logs can be omitted with flags.
"""

from __future__ import annotations

import argparse
import json
import sqlite3
from pathlib import Path
from typing import Any


def sql_quote(value: Any) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "1" if value else "0"
    if isinstance(value, (int, float)):
        return str(value)
    return "'" + str(value).replace("'", "''") + "'"


def emit_insert(table: str, row: dict[str, Any]) -> str:
    columns = ", ".join(row.keys())
    values = ", ".join(sql_quote(value) for value in row.values())
    return f"INSERT OR IGNORE INTO {table} ({columns}) VALUES ({values});"


def table_exists(conn: sqlite3.Connection, name: str) -> bool:
    row = conn.execute(
        "SELECT 1 FROM sqlite_master WHERE type='table' AND name=?",
        (name,),
    ).fetchone()
    return row is not None


def rows(conn: sqlite3.Connection, query: str) -> list[sqlite3.Row]:
    return list(conn.execute(query).fetchall())


def export(db_path: Path, include_users: bool, include_logs: bool) -> str:
    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row
    lines = [
        "-- Generated by cloudflare/license-api/scripts/export_ecs_sqlite_to_d1_sql.py",
        "BEGIN TRANSACTION;",
    ]

    if include_users and table_exists(conn, "accounts_user"):
        for row in rows(conn, "SELECT id, email, username, password, email_verified, registered_ip, date_joined FROM accounts_user"):
            # Django password hashes are not compatible with the Worker PBKDF2
            # verifier. Export users only for reference or manual password reset.
            lines.append(
                emit_insert(
                    "users",
                    {
                        "id": row["id"],
                        "email": row["email"],
                        "username": row["username"],
                        "password_hash": "RESET_REQUIRED",
                        "email_verified": 1 if row["email_verified"] else 0,
                        "registered_ip": row["registered_ip"],
                        "created_at": row["date_joined"],
                    },
                )
            )

    if table_exists(conn, "licensing_activation_code"):
        query = (
            "SELECT id, code, edition, license_days, max_devices, status, "
            "assigned_to_id, customer_name, customer_email, machine_fingerprint_prebind, "
            "notes, created_at, used_by_id, used_at FROM licensing_activation_code"
        )
        for row in rows(conn, query):
            lines.append(
                emit_insert(
                    "activation_codes",
                    {
                        "id": row["id"],
                        "code": row["code"],
                        "edition": row["edition"],
                        "license_days": row["license_days"],
                        "max_devices": row["max_devices"],
                        "status": row["status"],
                        "assigned_to_user_id": row["assigned_to_id"],
                        "customer_name": row["customer_name"],
                        "customer_email": row["customer_email"],
                        "machine_fingerprint_prebind": row["machine_fingerprint_prebind"],
                        "notes": row["notes"],
                        "created_at": row["created_at"],
                        "used_by_user_id": row["used_by_id"],
                        "used_at": row["used_at"],
                    },
                )
            )

    if table_exists(conn, "licensing_license"):
        query = (
            "SELECT id, user_id, activation_code_id, license_id, edition, machine_fingerprint, "
            "machine_fingerprint_history, signed_payload, signature, nonce, issued_at, expires_at, "
            "is_active, revoked, revoke_reason, approval_status, last_online_check, max_offline_days, "
            "suspicious_flag, created_at FROM licensing_license"
        )
        for row in rows(conn, query):
            signed_payload = row["signed_payload"]
            if not isinstance(signed_payload, str):
                signed_payload = json.dumps(signed_payload or {}, ensure_ascii=False)
            lines.append(
                emit_insert(
                    "licenses",
                    {
                        "id": row["id"],
                        "user_id": row["user_id"],
                        "activation_code_id": row["activation_code_id"],
                        "license_id": row["license_id"],
                        "edition": row["edition"],
                        "machine_fingerprint": row["machine_fingerprint"],
                        "machine_fingerprint_history": row["machine_fingerprint_history"] or "[]",
                        "signed_payload": signed_payload,
                        "signature": row["signature"],
                        "nonce": row["nonce"],
                        "issued_at": row["issued_at"],
                        "expires_at": row["expires_at"],
                        "is_active": 1 if row["is_active"] else 0,
                        "revoked": 1 if row["revoked"] else 0,
                        "revoke_reason": row["revoke_reason"],
                        "approval_status": row["approval_status"],
                        "last_online_check": row["last_online_check"],
                        "max_offline_days": row["max_offline_days"],
                        "suspicious_flag": 1 if row["suspicious_flag"] else 0,
                        "created_at": row["created_at"],
                    },
                )
            )

    if table_exists(conn, "releases_version"):
        query = (
            "SELECT id, version, channel, edition, release_notes, download_url, "
            "file_hash_sha256, file_size_bytes, is_required, released_at FROM releases_version"
        )
        for row in rows(conn, query):
            lines.append(
                emit_insert(
                    "release_versions",
                    {
                        "id": row["id"],
                        "version": row["version"],
                        "channel": row["channel"],
                        "edition": row["edition"],
                        "release_notes": row["release_notes"],
                        "download_url": row["download_url"],
                        "file_hash_sha256": row["file_hash_sha256"],
                        "file_size_bytes": row["file_size_bytes"],
                        "is_required": 1 if row["is_required"] else 0,
                        "released_at": row["released_at"],
                    },
                )
            )

    if include_logs and table_exists(conn, "licensing_validation_log"):
        lines.append("-- Validation/usage logs are intentionally skipped by default.")

    lines.append("COMMIT;")
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--db", type=Path, default=Path("server/db.sqlite3"))
    parser.add_argument("--out", type=Path, default=Path("cloudflare/license-api/migrations/9000_import_from_ecs.sql"))
    parser.add_argument("--include-users", action="store_true")
    parser.add_argument("--include-logs", action="store_true")
    args = parser.parse_args()

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(export(args.db, args.include_users, args.include_logs), encoding="utf-8")
    print(f"Wrote {args.out}")


if __name__ == "__main__":
    main()
